from pathlib import Path
import json,shutil
root=Path(__file__).resolve().parents[1];out=root/"public"
data={"metadata":json.loads((out/"references/manifest.json").read_text()),"levels":[json.loads((root/f"src/data/level{i}.json").read_text()) for i in range(4)],"site":json.loads((root/"src/data/site.json").read_text()),"childcareSite":json.loads((root/"src/data/childcare-site.json").read_text())}
(out/"model/school-data.json").write_text(json.dumps(data,indent=2))
shutil.copy(root/"verification/geometry.json",out/"model/geometry-audit.json")
shutil.copy(root/"verification/functional.json",out/"model/browser-audit.json")
rows=''.join(f'<tr><td>Level {d["level"]}</td><td>{d["label"]}</td><td>{len(d["rooms"])}</td><td>{d["elevation"]:+.1f} m · assumed</td></tr>' for d in data['levels'])
html="""<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NE Oakville | Accuracy and QA/QC</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f4ed;color:#223930;font:16px/1.7 system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:64px 28px}header{border-bottom:1px solid #cbd2c6;padding-bottom:28px}h1{font-size:42px;line-height:1.15;font-weight:500;letter-spacing:-1.5px}h2{font-size:23px;font-weight:500;margin-top:42px}a{color:#1c6c61}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:12px;text-align:left;border-bottom:1px solid #d6dace}.kicker{font-size:12px;letter-spacing:2px}.notice{border-left:3px solid #ab8544;padding:12px 22px;background:#ebe7d9}.pass{color:#386e51}@media(max-width:600px){main{padding:30px 20px}h1{font-size:32px}table{font-size:12px}td,th{padding:7px}}
</style><main><header><a href="./">← Open the 3D viewer</a><p class="kicker">NE OAKVILLE HIGH SCHOOL · RECONSTRUCTION RECORD</p><h1>Accuracy & QA/QC</h1><p>Four levels, 208 room and support-space polygons, and campus context reconstructed from ten supplied photographs of seven architectural presentation sheets.</p></header>
<p class="notice">This is an independent, source-informed interpretation. It is not a measured survey, official BIM model or construction document. The photographs do not establish exact dimensions, grading or building heights.</p>
<h2>Source coverage</h2><p>Level 0: Photo 10. Level 1: Photos 7–9, with Photo 8 as the common coordinate frame. Level 2: Photo 4. Level 3: Photos 1 and 5. Campus: Photo 3. North/south elevations: Photo 6. Street perspective: Photo 2. Original drawings credited to sn/architects and the Halton District School Board.</p>
<table><thead><tr><th>Level</th><th>Program</th><th>Spaces</th><th>Model elevation</th></tr></thead><tbody>ROWS</tbody></table>
<h2>Verified in the model</h2><ul>
<li class="pass">All 208 room polygons are valid and have nonzero area.</li><li class="pass">No room-to-room or room-to-circulation overlap exceeds 0.5 m² at the assumed scale on any individual level.</li><li>Main wings, courtyard, east forecourt, three gym bays, upper science/arts/classroom areas and lower childcare program follow the photographs.</li><li>Workshop vertical relationships were reviewed against the upper plans: innovation has an occupied floor above; transportation and construction are partly double height with support rooms over their southern strips; manufacturing is predominantly double height.</li><li>Gym and cafeteria lower roof masses are distinct from the upper academic roofs. Level 2 and Level 3 voids are not filled with occupiable room slabs.</li><li>Stair footprints overlap across levels; centroid differences range from 0 to approximately 1.11 m at the assumed scale. This supports approximate registration, not surveyed alignment.</li><li>Walkable corridor/commons regions form one component per level when a 0.7 m schematic wall tolerance is allowed. This is not verification of every door, access route or code requirement.</li></ul>
<h2>Functional checks on Velocity</h2><p>The automated Chromium suite passed 28 checks: four floor selectors and room counts; real canvas picking; room evidence; all ten source images; exploded floors; labels; section clipping; camera controls; all-floor GLB export; and desktop/mobile viewport sizing. Source geometry, builds, browser QA and publishing commands were executed on the Velocity compute server. Rendering batches repeated details to reduce draw calls.</p>
<h2>Unresolved evidence and limitations</h2><ul>
<li>Horizontal scale is an assumed 0.14 metres per Photo 8 pixel. All lengths, areas and exported metric coordinates inherit this uncertainty.</li><li>Storey heights use 4.2 m increments; typical upper roof is 12.6 m above Level 1. Roof/parapet, slab, wall and opening dimensions are inferred.</li><li>Two small Level 2 edge discrepancies remain against the tall-space footprints: approximately 2.05 m² at the cafeteria and 3.86 m² at the drama space. Resolving them reliably needs dimensioned plans or CAD.</li><li>Approximately 95.4% of the reconstructed childcare footprint falls beneath the traced gym/change/storage/circulation suite. The remaining 4.6% reflects uncertain registration in the oblique Level 0 photograph.</li><li>North is an estimated 40° clockwise from drawing-up, interpreted from the photographed arrows; the model is not georeferenced. Sixth Line is at drawing-right and Burnhamthorpe Road at drawing-bottom.</li><li>Façade materials and massing are source-informed. Repetitive window modules, unseen faces, interior furnishings, partition openings, stair flights, roof equipment, planting and terrain details are schematic. Lower childcare terrain is a visualization of the falling-grade relationship, not a civil grading design.</li><li>Interior partitions use a cutaway display height. No structural, MEP, fire-rating, accessibility, construction or as-built compliance verification is claimed.</li></ul>
<h2>Inspect and reuse</h2><p>Use the floor selector and “Find a space” to inspect room evidence. Source images 4, 5 and 8 support an optional traced-space overlay. “Plan” uses drawing orientation; the compass updates with the camera.</p>
<p><a href="model/ne-oakville-school.glb">Building GLB · all four levels</a><br><a href="model/ne-oakville-campus.glb">Campus GLB · building and site context</a><br><a href="model/school-data.json">Semantic model data</a><br><a href="model/geometry-audit.json">Geometry audit JSON</a><br><a href="model/browser-audit.json">Browser audit JSON</a><br><a href="model/final-audit.json">Final model and overlay audit JSON</a><br><a href="https://github.com/ConDigitalExpert/ne-oakville-school-3d">Source repository and reconstruction scripts</a></p>
<p class="kicker">REVIEWED 26 SEPTEMBER 2026 · DIMENSIONS INFERRED</p></main></html>"""
(out/"QA-QC.html").write_text(html.replace("ROWS",rows))
