import {chromium} from '@playwright/test';import fs from 'node:fs/promises';
const report={time:new Date().toISOString(),checks:[],errors:[],consoleErrors:[]};let browser;
const check=(name,pass,detail)=>{report.checks.push({name,pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail));};
try{
browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1600,height:1050},deviceScaleFactor:1});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});
await page.goto(process.env.QA_URL||'http://localhost:4173',{waitUntil:'networkidle'});await page.waitForFunction(()=>!!window.__school);await page.waitForTimeout(1800);
for(const level of [0,1,2,3]){await page.locator('[data-level="'+level+'"]').click();const state=await page.evaluate(n=>({selected:__school.selectedLevel,visible:__school.floorGroups.map(g=>g.visible),expected:__school.levels[n].rooms.length,actual:__school.rooms.filter(o=>o.userData.level===n).length,site:__school.site.visible}),level);check('Level '+level,state.selected===String(level)&&state.visible.every((v,i)=>v===(i===level))&&state.actual===state.expected,state);}
await page.evaluate(()=>__school.selectRoom(__school.rooms.find(o=>o.userData.level===3)));const metadata=await page.locator('#roomCard').innerText();check('Room metadata',metadata.includes('LEVEL 03')&&metadata.includes('inferred'),metadata);await page.locator('#closeRoom').click();
await page.locator('#sources').click();for(let n=0;n<10;n++){await page.locator('[data-source="'+n+'"]').click();await page.waitForFunction(()=>{let i=document.getElementById('sourceImage');return i.complete&&i.naturalWidth>0;});const image=await page.locator('#sourceImage').evaluate(i=>({src:i.src,width:i.naturalWidth,height:i.naturalHeight}));check('Source '+(n+1),image.width>100&&image.height>100,image);}await page.locator('#closeSources').click();
await page.locator('label:has(#explode)').click();let exploded=await page.evaluate(()=>({visible:__school.floorGroups.map(g=>g.visible),positions:__school.floorGroups.map(g=>g.position.y),exterior:__school.exterior.visible}));check('Exploded floors',exploded.visible.every(Boolean)&&!exploded.exterior&&exploded.positions[3]>30,exploded);
await page.locator('label:has(#labels)').click();check('Labels on',await page.evaluate(()=>__school.labels.every(l=>l.visible)));await page.locator('label:has(#labels)').click();
await page.locator('#section').fill('40');await page.locator('#section').dispatchEvent('input');const clipping=await page.evaluate(()=>{let m=__school.rooms[0].material;return {enabled:__school.renderer.localClippingEnabled,count:m.clippingPlanes.length,constant:m.clippingPlanes[0].constant};});check('Section clipping',clipping.enabled&&clipping.count===1&&clipping.constant<100,clipping);
await page.locator('[data-camera="site"]').click();await page.waitForTimeout(1300);const campus=await page.evaluate(()=>__school.controls.target.toArray());check('Campus view',campus[2]<-80,campus);await page.locator('#reset').click();await page.waitForTimeout(1300);const reset=await page.evaluate(()=>({target:__school.controls.target.toArray(),clip:__school.rooms[0].material.clippingPlanes[0].constant}));check('Reset camera and clipping',Math.abs(reset.target[2])<1&&reset.clip===200,reset);
await page.locator('label:has(#explode)').click();await page.locator('[data-level="1"]').click();await page.locator('[data-camera="top"]').click();await page.waitForTimeout(1300);
// Actual canvas picking in plan view, using projected floor center.
const clickPoint=await page.evaluate(()=>{const mesh=__school.rooms.find(o=>o.userData.level===1&&o.userData.room.category==='classroom')||__school.rooms.find(o=>o.userData.level===1);mesh.geometry.computeBoundingBox();const v=mesh.geometry.boundingBox.getCenter(mesh.position.clone());mesh.localToWorld(v);v.project(__school.camera);const r=__school.renderer.domElement.getBoundingClientRect();return {x:r.x+(v.x+1)*r.width/2,y:r.y+(1-v.y)*r.height/2,name:mesh.userData.room.name};});
await page.mouse.click(clickPoint.x,clickPoint.y);check('Canvas ray picking',await page.locator('#roomCard').isVisible(),{...clickPoint,text:await page.locator('#roomName').textContent()});await page.screenshot({path:'verification/functional-level1.png'});
const glb=await page.evaluate(async()=>{const a=await __school.exportGLB();const v=new DataView(a),len=v.getUint32(12,true);let json=JSON.parse(new TextDecoder().decode(new Uint8Array(a,20,len)));return {magic:v.getUint32(0,true),bytes:a.byteLength,nodes:json.nodes.length,levelNames:__school.levels.map(l=>l.label),nodeNames:json.nodes.filter(n=>n.name&&__school.levels.some(l=>l.label===n.name)).map(n=>n.name)};});check('GLB binary all four levels',glb.magic===0x46546c67&&glb.bytes>1000&&glb.levelNames.every(n=>glb.nodeNames.includes(n)),glb);
for(const viewport of [{width:1600,height:1050},{width:390,height:844}]){await page.setViewportSize(viewport);await page.waitForFunction(()=>{const c=__school.renderer.domElement,h=document.getElementById('viewport');return c.clientWidth===h.clientWidth&&c.clientHeight===h.clientHeight});const metrics=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth,scrollHeight:document.documentElement.scrollHeight,height:innerHeight,buttons:[...document.querySelectorAll('#levels button,.view-tools button,.outline')].map(b=>({text:b.innerText,size:parseFloat(getComputedStyle(b).fontSize),width:b.getBoundingClientRect().width})),canvas:[__school.renderer.domElement.clientWidth,__school.renderer.domElement.clientHeight]}));check('Responsive '+viewport.width,metrics.scrollWidth<=viewport.width&&metrics.scrollHeight<=viewport.height&&metrics.canvas[0]>100&&metrics.canvas[1]>100,metrics);check('Button font '+viewport.width,metrics.buttons.every(b=>b.size>=12),metrics.buttons);await page.screenshot({path:'verification/functional-'+viewport.width+'.png'});}
check('No browser errors',report.errors.length===0&&report.consoleErrors.length===0,{errors:report.errors,consoleErrors:report.consoleErrors});
}catch(e){report.fatal=e.stack;console.error(e);}finally{if(browser)await browser.close();report.passed=!report.fatal&&report.checks.every(c=>c.pass);await fs.writeFile('verification/functional.json',JSON.stringify(report,null,2));}

