import registration from './data/registration.json';
import './style.css';import * as THREE from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';import {buildModel,levels,colors} from './model.js';
const $=id=>document.getElementById(id);const host=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#e7eade');scene.fog=new THREE.Fog('#e7eade',390,800);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;renderer.localClippingEnabled=true;host.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(35,1,.1,2000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=18;controls.maxDistance=650;
scene.add(new THREE.HemisphereLight('#fff9ed','#a0ad91',2.5));const sun=new THREE.DirectionalLight('#fff2d8',3.3);sun.position.set(-80,130,70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-130,right:130,top:130,bottom:-130,near:1,far:350});sun.shadow.normalBias=.14;sun.shadow.bias=-.00015;sun.shadow.radius=3;scene.add(sun);scene.add(new THREE.AmbientLight('#ffffff',.3));
const model=buildModel();scene.add(model.site,model.building);const clip=new THREE.Plane(new THREE.Vector3(0,0,-1),200);
model.building.traverse(o=>{if(o.isMesh){const m=Array.isArray(o.material)?o.material:[o.material];m.forEach(a=>{a.clippingPlanes=[clip];a.clipShadows=true;});}});
let renderDirty=true;controls.addEventListener('change',()=>{renderDirty=true;});let selectedLevel='all',selected=null,exploded=false,showLabels=false,cameraTween=null;
function toast(s){$('toast').textContent=s;$('toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.opacity=0,3500);}
let previousAspect=0;function resize(){const w=host.clientWidth,h=host.clientHeight,next=w/h;if(previousAspect){const factor=Math.min(1,previousAspect)/Math.min(1,next);camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);}renderer.setSize(w,h);camera.aspect=next;previousAspect=next;camera.updateProjectionMatrix();renderDirty=true;}new ResizeObserver(resize).observe(host);resize();
const poses={iso:[[155,127,175],[0,2,0]],street:[[200,22,10],[20,5,0]],top:[[0,220,.1],[0,0,0]],north:[[121.6,35,-146.3],[0,5,0]],south:[[-121.6,35,146.3],[0,5,0]],site:[[250,580,290],[-25,0,-120]]};
function view(name,instant=false){const [pos,target]=poses[name]||poses.iso;const p=new THREE.Vector3(...pos),t=new THREE.Vector3(...target);if(selectedLevel!=='all'&&name!=='site'){const data=levels[Number(selectedLevel)],points=data.rooms.flatMap(r=>r.polygon),xs=points.map(a=>(a[0]-640)*.14),zs=points.map(a=>(a[1]-480)*.14),cx=(Math.min(...xs)+Math.max(...xs))/2,cz=(Math.min(...zs)+Math.max(...zs))/2,scale=Math.max(.3,Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...zs)-Math.min(...zs))/106),center=new THREE.Vector3(cx,data.elevation,cz);p.sub(t).multiplyScalar(scale*(name==='top'?1.15:1)).add(center);t.copy(center);}if(camera.aspect<.9&&name!=='site')p.sub(t).multiplyScalar(1.35).add(t);if(instant){camera.position.copy(p);controls.target.copy(t);controls.update();}else cameraTween={start:performance.now(),from:camera.position.clone(),to:p,tf:controls.target.clone(),tt:t};document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===name));}view('iso',true);
function clearSelected(){renderDirty=true;if(selected)selected.material.emissive.setHex(0);selected=null;$('roomCard').hidden=true;}
function display(){renderDirty=true;clearSelected();model.exterior.visible=selectedLevel==='all'&&!exploded;model.floorGroups.forEach((g,i)=>{g.visible=selectedLevel==='all'?true:i===Number(selectedLevel);g.position.y=levels[i].elevation+(exploded?i*11:0);});model.labels.forEach(l=>l.visible=showLabels&&selectedLevel!=='all'||showLabels&&exploded);model.site.visible=$('site').checked&&selectedLevel!=='0';$('viewTitle').textContent=selectedLevel==='all'?(exploded?'A building, unfolded':'The complete building'):['Lower level · Childcare','First floor · Community','Second floor · Learning','Third floor · Discovery'][Number(selectedLevel)];$('legend').hidden=selectedLevel==='all'&&!exploded;window.__school.selectedLevel=selectedLevel;}
function selectLevel(level){selectedLevel=String(level);document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',b.dataset.level===selectedLevel));display();$('roomSearch').value='';view(document.querySelector('[data-camera].active')?.dataset.camera||'iso');if(selectedLevel!=='all'){toast('Select a room to inspect its source evidence');}}
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>selectLevel(b.dataset.level));document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>view(b.dataset.camera));$('reset').onclick=()=>{view('iso');$('section').value=100;clip.constant=200;$('sliceValue').textContent='Full';};
$('explode').onchange=e=>{exploded=e.target.checked;if(exploded&&selectedLevel!=='all'){selectedLevel='all';document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',b.dataset.level==='all'));}display();if(exploded){controls.target.y=19;toast('Floors separated vertically · heights exaggerated');}};
$('labels').onchange=e=>{showLabels=e.target.checked;display();};$('site').onchange=display;$('section').oninput=e=>{renderDirty=true;const v=Number(e.target.value);clip.constant=v===100?200:-48+v*1.03;$('sliceValue').textContent=v===100?'Full':v+'%';};$('closeRoom').onclick=clearSelected;
$('legend').innerHTML=Object.entries(colors).filter(([k])=>['classroom','science','arts','athletics','commons','childcare'].includes(k)).map(([k,c])=>'<span><i style="background:'+c+'"></i>'+k[0].toUpperCase()+k.slice(1)+'</span>').join('');
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down={x:0,y:0};renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('click',e=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5||selectedLevel==='all'&&!exploded)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(model.rooms).find(h=>h.object.parent.visible&&clip.distanceToPoint(h.point)>=0);if(hit)selectRoom(hit.object);else clearSelected();});
function selectRoom(mesh){clearSelected();selected=mesh;mesh.material.emissive.set('#52633d');mesh.material.emissiveIntensity=.35;const {room,level}=mesh.userData;$('roomType').textContent=room.category.toUpperCase();$('roomName').textContent=room.name;$('roomLevel').textContent='LEVEL 0'+level;$('roomConfidence').textContent=(room.confidence||'inferred').toUpperCase();$('roomNotes').textContent=(room.notes||'Room footprint interpreted from presentation plan.')+' All dimensions inferred.';$('roomCard').hidden=false;}
$('roomSearch').innerHTML+=[...model.rooms].sort((a,b)=>a.userData.level-b.userData.level||a.userData.room.name.localeCompare(b.userData.room.name)).map(mesh=>'<option value="'+mesh.userData.room.id+'">L'+mesh.userData.level+' · '+mesh.userData.room.name+'</option>').join('');
$('roomSearch').onchange=e=>{const mesh=model.rooms.find(m=>m.userData.room.id===e.target.value);if(!mesh)return;$('explode').checked=false;exploded=false;selectLevel(mesh.userData.level);cameraTween=null;$('roomSearch').value=mesh.userData.room.id;selectRoom(mesh);const box=new THREE.Box3().setFromObject(mesh),p=box.getCenter(new THREE.Vector3());controls.target.copy(p);camera.position.copy(p.clone().add(new THREE.Vector3(22,35,28)));controls.update();};
const sourceNames=['Third floor plan','Street perspective','Campus site plan','Second floor plan','Third floor alternate','North & south elevations','First floor plan','First floor reference','First floor alternate','Lower level plan'];let sourceIndex=1;function source(n){sourceIndex=n;refreshOverlay(n);$('sourceImage').src=import.meta.env.BASE_URL+'references/'+(n+1)+'-Photo-'+(n+1)+'.jpg';$('sourceCaption').textContent='Board '+String(n+1).padStart(2,'0')+' · '+sourceNames[n]+' · sn/architects · Undimensioned presentation image; reconstruction is interpretive.';document.querySelectorAll('[data-source]').forEach(b=>b.classList.toggle('active',Number(b.dataset.source)===n));}
function refreshOverlay(n){const photo=String(n+1),reg=registration.photos[photo],lev=photo==='8'?1:reg?.level;const valid=lev!==undefined;$('overlayToggle').disabled=!valid;$('overlayStatus').textContent=valid?'':'Available on plans 4, 5 and 8';$('traceOverlay').style.display=valid&&$('overlayToggle').checked?'block':'none';if(!valid)return;const inv=reg?.canonicalToSource;const tr=([x,y])=>{if(!inv)return[x,y];const z=inv[2][0]*x+inv[2][1]*y+inv[2][2];return[(inv[0][0]*x+inv[0][1]*y+inv[0][2])/z,(inv[1][0]*x+inv[1][1]*y+inv[1][2])/z];};$('traceOverlay').innerHTML=levels[lev].rooms.map(r=>'<polygon points="'+r.polygon.map(p=>tr(p).join(',')).join(' ')+'" fill="'+colors[r.category]+'" fill-opacity=".25" stroke="#0a706b" stroke-width="1.5"><title>'+r.name+'</title></polygon>').join('');}
$('overlayToggle').onchange=()=>refreshOverlay(sourceIndex);
$('sourceNav').innerHTML=sourceNames.map((s,n)=>'<button data-source="'+n+'">'+String(n+1).padStart(2,'0')+' / '+s+'</button>').join('');document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>source(Number(b.dataset.source)));$('sources').onclick=()=>{source(selectedLevel==='all'?1:({0:9,1:7,2:3,3:4})[selectedLevel]);$('sourceDialog').showModal();};$('closeSources').onclick=()=>$('sourceDialog').close();$('sourceDialog').addEventListener('click',e=>{if(e.target===$('sourceDialog'))$('sourceDialog').close();});
async function exportGLB(includeSite=false){const copy=model.building.clone(true);copy.traverse(o=>{if(o.isSprite)o.visible=false;if(o.isMesh){o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{m.clippingPlanes=[];m.clipShadows=false;});}});copy.children.forEach((g,i)=>{if(i<4){g.visible=true;g.position.y=levels[i].elevation;}else g.visible=true;});const output=new THREE.Group();output.name='NE Oakville reconstruction — dimensions inferred';output.add(copy);if(includeSite){const campus=model.site.clone(true);campus.getObjectByName('Backdrop ground')?.removeFromParent();campus.visible=true;output.add(campus);}return await new GLTFExporter().parseAsync(output,{binary:true,onlyVisible:true});}
$('download').onclick=async e=>{e.preventDefault();toast('Preparing architectural model…');try{const result=await exportGLB();const url=URL.createObjectURL(new Blob([result],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download='NE-Oakville-interpretive-model.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('3D model downloaded · Inferred geometry');}catch(err){console.error(err);toast('Model export could not finish. Please try again.');}};
window.__school={scene,camera,renderer,controls,...model,levels,selectLevel,selectRoom,view,exportGLB,selectedLevel};
display();function animate(){requestAnimationFrame(animate);if(cameraTween){let t=Math.min(1,(performance.now()-cameraTween.start)/900);let u=1-Math.pow(1-t,3);camera.position.lerpVectors(cameraTween.from,cameraTween.to,u);controls.target.lerpVectors(cameraTween.tf,cameraTween.tt,u);if(t===1)cameraTween=null;}controls.update();const north=new THREE.Vector3(.64,0,-.77).transformDirection(camera.matrixWorldInverse);document.querySelector('.compass b').style.transform='rotate('+((Math.atan2(north.x,north.y)*180/Math.PI)-45)+'deg)';if(renderDirty||cameraTween){renderer.render(scene,camera);renderDirty=false;}}animate();

